### PR TITLE
Added documentation for viewing current preferences file

### PR DESCRIPTION
**Pull request by IanCoolidge0**
I'm not entirely sure what should go into pushing to this for now, so close this if you want to.

### CODE REVIEW

**Comment by virtigo** [comment]
Two quick questions:
1. is there any reason to navigate to the directory with your local preference file before sshing in?
2. is it okay if I change the `less` command to just use `cat`? It's a small file, and `cat networktables.ini` will just print the contents to the console. That way people don't need to worry about exiting less.

**Comment by virtigo** [comment]
Oh, one more thing. In the future forking the repository, making changes there, and then pull requesting would be a better way. Then we don't have to worry about deleting branches for every pull request. Thanks for the extra info by the way!

**Comment by lgebhardt** [comment]
@virtigo Getting the process of forking (and PRs from there) documented would be good. I assume you already have that planned, but if not...

**Comment by IanCoolidge0** [comment]
@virtigo You can make both of those changes. I forgot to change the line for the first part, and the only reason I put less as opposed to cat is because that's what I did through the season.

Also, thanks for the info on forking as opposed to direct pull requests, this was really more of an example to see how this would work in the future.

**Comment by virtigo** [comment]
To both of you, as it says in the README, there is git documentation planned, and there's an entire folder for it. However, it's a rather complicated subject to tackle so I'm working closely with Ben and Kurtis on writing it. It's the next thing being worked on.

**Pull request merged**
